x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider distributions you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  # image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:3.1.3}
  build:
    context: .
    dockerfile: ./Dockerfile.airflow
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    # yamllint disable rule:line-length
    # Use simple http server on scheduler for health checks
    # See https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/check-health.html#scheduler-health-check-server
    # yamllint enable rule:line-length
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'

    # Point to DAGs folder in the mounted project
    AIRFLOW__CORE__DAGS_FOLDER: '/opt/airflow/logistics_analytics_project/pipelines/dags'
    # Point to logs folder in the mounted project
    AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/logistics_analytics_project/pipelines/logs"

    # Optimization for low memory environment (4GB RAM)
    AIRFLOW__SCHEDULER__PARSING_PROCESSES: 1 # limits the scheduler to parsing one DAG at a time
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 60 # 30s -> 60s. The scheduler will check for DAG updates less frequently
    AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: 120
    AIRFLOW__SCHEDULER__JOB_HEARTBEAT_SEC: 30
    
  
  volumes:
    # Mount the entire repository root for development
    - ${AIRFLOW_PROJ_DIR:-.}/:/opt/airflow/logistics_analytics_project


  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy



services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 3
      start_period: 5s
    restart: always


  airflow-apiserver:
    <<: *airflow-common   # ← "Copy all config from airflow-common here"
    command: api-server   # ← Plus override/add this
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully


  airflow-scheduler:
    <<: *airflow-common  # ← "Copy all config from airflow-common here"
    command: scheduler   # ← Plus override/add this
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

    working_dir: /opt/airflow/logistics_analytics_project

  airflow-dag-processor:
    <<: *airflow-common       # ← "Copy all config from airflow-common here"
    command: dag-processor    # ← Plus override/add this
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: /opt/airflow/logistics_analytics_project/scripts/init_airflow.sh
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    user: "0:0"

  duckdb:
    image: duckdb/duckdb
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    network_mode: host # for duckdb web ui

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
      target: dbt-third-party # name of the build stage from the Dockerfile you want to build and run.
      args:
        dbt_third_party: "dbt-duckdb"  # or whichever plugin you need
    image: my-dbt:latest
    volumes:
      - .:/workspace
      - ./dbt:/usr/app/dbt
      - ./.dbt:/root/.dbt
    working_dir: /usr/app/dbt/
    stdin_open: true
    tty: true
    command: sleep infinity
    ports:
      - "8081:8080" # for generated docs ui
    depends_on:
      - duckdb


volumes:
  postgres-db-volume:


