version: 1

sources:
  - name: raw_data
    description: >
      Raw data about transportation and logistics operations.
    database: logistics_tracking               
    schema: raw                         

    tables:
      - name: tracking_data
        description: >
          Tracking data for logistics operations.
          Some highlighted information: 
            - transportation details 
            - operations & gps 
            - suppliers & customers
            - transported materials
        columns:
          - name: "Booking ID"
            description: Unique identifier for each booking.
          - name: "Vehicle Registration"
            description: The unique registration number of the vehicle used for transportation.
          - name: "Driver Name"
            description: The name of the driver assigned to the trip.
          - name: "Driver Mobile No"
            description: The contact number of the driver.
          - name: "Customer Name"
            description: The name of the customer receiving the shipment.
          - name: "Supplier Name"
            description: The name of the supplier sending the shipment.
          - name: "Material Shipped"
            description: A description of the materials being transported in the shipment.
          - name: "Origin Location"
            description: The initial point from which the shipment starts.
          - name: "Origin Location Latitude"
            description: Latitude of the origin location.
          - name: "Origin Location Longitude"
            description: Longitude of the origin location.
          - name: "Destination Location"
            description: The final destination where the shipment is to be delivered.
          - name: "Destination Location Latitude"
            description: Latitude of the destination location.
          - name: "Destination Location Longitude"
            description: Longitude of the destination location.
          - name: "Gps Provider"
            description: GPS service provider tracking the vehicle.
          - name: "Data Ping time"
            description: The timestamp of the last recorded GPS data ping from the vehicle.
          - name: "Current Location"
            description: The most recent known location of the vehicle.
          - name: "Current Location Latitude"
            description: The latitude of the vehicle's current location.
          - name: "Curren Location Longitude"
            description: The longitude of the vehicle's current location.
          - name: "Shipment Type"
            description: Indicates whether the shipment is a Market (spot booking) or Regular (contract-based) trip.
          - name: "Transportation Distance (KM)"
            description: The total distance covered by the vehicle during the trip in kilometers.
          - name: "Ontime"
            description: Indicates whether the vehicle arrived on time (Yes/No).
          - name: "Booking Date"
            description: The date and time when the booking was created.
          - name: "Trip Start Date"
            description: The actual start date and time of the trip.
          - name: "Trip End Date"
            description: The estimate date and time of arrival.
          - name: "Planned ETA"
            description: The expected time of arrival at the destination as per the trip plan.
          - name: "Actual ETA"
            description: The actual time of arrival at the destination.
          - name: "Vehicle Type"
            description: The type of vehicle used for the shipment (e.g., 32 FT Truck, Tata Ace, Multi-Axle).
          - name: "Minimum Kms To Be Covered In A Day"
            description: The minimum distance the vehicle is expected to cover in a single day.
          